### ISSUE TITLE
withEnvironmentVariable settings not available in separate thread

### ISSUE THREAD

**Issue by chefhoobajoob** [webcompere/system-stubs#35]
I have some test targets that, when run, launch a thread pool and run the tested code on threads from this pool (the test doesn't do this, it's the nature of the code under test). I am finding on Java 11 (eclipse 11.0.12+7), a call to `System.getenv()` in the body of the `withEnvironmentVariable().execute()` lambda returns the modified environment variables, but when `System.getenv()` is invoked from the code being tested in the thread pool, I'm finding that *none* of the test settings are present in that context.

Is this expected? We just recently updated our builds and test execution from Java 8 to 11, and all our tests started failing this way.

**Comment by ashleyfrieze** [comment]
Can you reproduce the issue in a simpler form? In other words can you simulate it in a test case you can share? ‘System.getenv’ should be global and transcend all threads.

**Comment by chefhoobajoob** [comment]
I am going to try and do that, yes. Seems odd to me, so I'm hoping trying this will highlight something obvious I'm missing.

**Comment by ashleyfrieze** [comment]
It's worth noting that multi-threaded code can run in its own timings. This
may be a synchronization issue. `withEnvironmentVariables` puts the
environment back as it was at the end of `execute`. Are you sure your
worker threads have terminated before that happens?

**Comment by chefhoobajoob** [comment]
Yes, that was in fact the problem. Not sure what it was about the changes we made, but they were enough to reliably reveal this race condition. Nothing to see here!
