### ISSUE TITLE
Resources.with not working with Windows

### ISSUE THREAD

**Issue by davecramer** [webcompere/system-stubs#39]
```
Resources.with(
        new EnvironmentVariables(PGEnvironment.PGPASSFILE.getName(), "", "APPDATA", urlPath.getPath() ),
        new SystemProperties(PGEnvironment.ORG_POSTGRESQL_PGPASSFILE.getName(), "",  "user.home", urlPath.getPath())
    ).execute(() -> {
```

The SystemProperty is not available in the lambda. This works on macos and linux, but not windows.

**Comment by ashleyfrieze** [comment]
Hey @davecramer  - I notice you've closed this. I was going to suggest checking whether you can set ANY system property this way. I'd expect you to be able to.

**Comment by davecramer** [comment]
Ya, it was a brain fart on my part.

**Comment by ashleyfrieze** [comment]
@davecramer they happen
