### ISSUE TITLE
"Live" Environment Variables in @SpringBootTest RANDOM_PORT app aren't found

### ISSUE THREAD

**Issue by sdoxsee** [webcompere/system-stubs#43]
If you have a `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)` like the [provided example](https://github.com/webcompere/system-stubs/blob/main/system-stubs-jupiter/src/test/java/uk/org/webcompere/systemstubs/jupiter/examples/SpringAppWithDynamicPropertiesTest.java), environment variables in the servlet container won't get picked up after the ApplicationContext is initialized. In fact, `System.getenv` will get `null` even for values that were available during startup and that are still "live" in the test case.

If tests are `@SpringBootTest` or `@WebMvcTest` then the default is MockMvc environment and a servlet container isn't started up. This allows the environment variables to affect the mock environment, even after the ApplicationContext is initialized.

I imagine that the values are being provided initially and then look no further because the servlet container is in a completely different process. 

I can understand the limitation but wasn't clear to me without some testing. Perhaps some more documentation would help. I created a repo with some of my testing and found that ` SpringBootTestRandomPortTest.springBootTest` fails on [this line](https://github.com/sdoxsee/system-stubs-sample/blob/2dec6b1db0ef0b05576a65ae14552e086fc8bf5a/src/test/java/com/example/systemstubssample/SystemStubsSampleApplicationTests.java#L71) because the environment variable value is neither the original, nor the new...but `null`.

Feel free to close this issue but leaving it here for others that may find it helpful.

Great project. Thanks!

**Comment by ashleyfrieze** [comment]
MockMvc has a different lifecycle as you say. If you wish to add some documentation as a PR, then please do. Perhaps a child document on `Environment Variables and Spring Tests` we can link from the main README. Feel free to add your example tests to the Spring examples too.

**Comment by ashleyfrieze** [comment]
@sdoxsee ^^^

**Comment by sdoxsee** [comment]
Going to close this for now but may come back with a PR some other time. Thanks!
