### ISSUE TITLE
Mockito v5.0.0 defaults MockMaker to `mockito-inline`

### ISSUE THREAD

**Issue by DeepController** [webcompere/system-stubs#49]
Mockito v5.0.0 release note: https://github.com/mockito/mockito/releases/tag/v5.0.0

> ## Switch the default mockmaker to `mockito-inline`
> Back in Mockito 2.7.6, we published a new mockmaker based on the "inline bytecode" principle.
This mockmaker creates mocks manipulating bytecode equivalent within the original class such that its method implementations hook into the normal Mockito machinery.
As a comparison, the subclass mockmaker generates "real" subclasses for mocks, to mimic the same behavior.
While the approaches are similar, the inline mockmaker avoids certain restrictions that the JDK imposes.
For example, it does not violate module boundaries (introduced in JDK 9, but more heavily used in JDK 17) and avoids the leaking of the creation of the subclass.

Any plan to switch to Mockito v5 (even though this would bump the minimum supported JDK version to JDK11)? Thanks!

**Comment by ashleyfrieze** [comment]
@DeepController - no immediate plans to do that. I've got another problem with the use of mockito as is: #45 - where the static mock made for the environment variables only applies to the current thread. If Mockito v5 fixed that, or gave me a better way to do static mocks for `getenv`, then I'd be more interested.

Feel free to propose a PR if you would like to. I'm ok with bumping minimum Java to 11. For <11, there's always the v1 release train of this project.

**Comment by ashleyfrieze** [comment]
As the solution no longer depends on Mockito at runtime, this can be closed.
