### ISSUE TITLE
SystemStubsExtension illegal access to AnnotationUtils(org.junit.platform.commons)

### ISSUE THREAD

**Issue by mabanos** [webcompere/system-stubs#50]
I'm migrating my project to modules and SystemStubsExtension uses some utils classes that it shouldn't from junit-platform-commons:1.6.2.

junit-platform-commons contains a module-info.java after 1.4.2 that exports the package org.junit.platform.commons.util only to other junit modules.

![image](https://user-images.githubusercontent.com/9824493/214825709-9dc9f63b-9f24-4524-9f9f-b0396b67ee1c.png)

So, the illegal access from SystemStubsExtension results in the following error:

![image](https://user-images.githubusercontent.com/9824493/214825907-0f80e80f-e9bf-4299-881b-e573a1012f59.png)

**Comment by ashleyfrieze** [comment]
Ah. We probably need to update the level of JUnit used here. Would you like to offer a PR?

**Comment by ashleyfrieze** [comment]
Note: https://github.com/webcompere/system-stubs/blob/main/system-stubs-jupiter/src/main/java/uk/org/webcompere/systemstubs/jupiter/SystemStubsExtension.java#L116 <- this is using the utility to find some fields with annotations - we may need to find a similar utility in JUnit or write one

**Comment by mabanos** [comment]
Thanks for your quick response. I cannot provide a PR right now, but, if I'm right, you're trying to get the static and non static fields of a class. You could use reflections for that:

https://stackoverflow.com/a/54223543

I cannot find the source at this moment, but investigating this problem I found someone who argued that this particular junit package (org.junit.platform.commons.util) should not be used, as it is intended for internal use (this is finally reflected in the module-info.java of the JAR).

So, we could say that, using the classpath, this system-stubs junit extension is compatible with junit 5.6.2. But if we use the module-path, the latest junit should be [5.4.2](https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api/5.4.2), which dependency is the 1.4.2 version of the [junit-platform-commons](https://mvnrepository.com/artifact/org.junit.platform/junit-platform-commons), being the latest that doesn't have a module-info.

**Comment by ashleyfrieze** [comment]
@miguemiguemigue sounds like we'll need to bring a fork of that JUnit helper into the local code. I can sort that some time. Ping me before you give it a try. Should be easy enough.

**Comment by ashleyfrieze** [comment]
> investigating this problem I found someone who argued that this particular junit package (org.junit.platform.commons.util) should not be used

@miguemiguemigue if the above relates to the error in SystemStubs, then please link the source of this discussion and I'll update them with the fix.

**Comment by ashleyfrieze** [comment]
The v2.0.2 release should avoid the reported issues. Just waiting for Nexus to release it. After that please retest @miguemiguemigue

**Comment by ashleyfrieze** [comment]
Nexus just let me hit the release button.

**Comment by ashleyfrieze** [comment]
@miguemiguemigue - despite the OSS front end being slow, and `search.maven.org` being down, it looks like v2.0.2 is released and can be tested, please see if it fixes your issue.

**Comment by mabanos** [comment]
@ashleyfrieze It's indeed fixed. Thank you very much for the quickness with which you have fixed the issue.

> > investigating this problem I found someone who argued that this particular junit package (org.junit.platform.commons.util) should not be used
> 
> @miguemiguemigue if the above relates to the error in SystemStubs, then please link the source of this discussion and I'll update them with the fix.

It wasn't a SystemStubs discussion, but a thread about using these internal junit utils classes, so there's no need to update about this fix.

Again, thank you =)

**Comment by ashleyfrieze** [comment]
@miguemiguemigue  - thanks for your helpful input and for re-testing. This is a small OSS project, and I don't have much time to put into Java at the moment, so help from the community is how we're able to keep things moving forwards.
