### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Frontrider** [webcompere/system-stubs#53]
Hello!

What is the license on this code?

**Comment by ashleyfrieze** [comment]
![image](https://user-images.githubusercontent.com/5574729/232034574-9d5ef271-13c6-4fa6-87aa-5f1243b1cd3f.png)

**Comment by ashleyfrieze** [comment]
https://github.com/webcompere/system-stubs/blob/main/LICENSE

@Frontrider ^^^
