### ISSUE TITLE
Lazy evaluation of EnvironmentVariables values

### ISSUE THREAD

**Issue by cwensel** [webcompere/system-stubs#55]
When using  @SystemStub on a field, the values on the map must be immediately available, but the value may not yet be initialized.

for example, when using Testcontainers, the image may not be started, thus a port value is not available. This prevents setting a new env var with the container port for use in a test.

Storing a Supplier lambda and resolving before each test invocation would resolve this.

**Comment by ashleyfrieze** [comment]
It would, but beforeEach can also be used to set any environment variables, etc you need to. By the time we get into beforeEach, the system stub object has been constructed.

**Comment by ashleyfrieze** [comment]
@cwensel  - I've used SystemStubs extensively with TestContainers - indeed, I wrote it to help me with TestContainers tests in JUnit 5. This example here - https://github.com/webcompere/system-stubs/blob/main/system-stubs-jupiter/src/test/java/uk/org/webcompere/systemstubs/jupiter/examples/SpringAppWithDynamicPropertiesTest.java#L55 where we're using Wiremock on a random port is an equivalent of how I'd solve things with TestContainers.

**Comment by cwensel** [comment]
Thanks for that. 

With the docker image loading on a static field, it works great, but it has to remain that way.

**Comment by ashleyfrieze** [comment]
@cwensel you can get the docker image to be on a non static field and initialise in `beforeEach`, but maybe that's expensive  in terms of time spent running docker processes.

The point is that you can set environment variables on the stub any time you like. The `@SystemStub` annotation hooks the object into the JUnit lifecycle, and will create one if you haven't already.

You can also mix the objects with the old SystemLambda syntax where you put the test code inside a lambda and ask the object to activate itself, run the test code, and then deactivate itself.

It should do what you expect it to.
