### ISSUE TITLE
Unable to read env var set in IDE

### ISSUE THREAD

**Issue by vvijayalakshmi21** [webcompere/system-stubs#70]
I am trying to read an env var using system-stubs that I will be supplying in the AWS lambda env vars in production.
Locally, it is given through the IntelliJ IDE's env vars.
I see that the value is null and not being injected. 

```
@Value("${bar}")
private String bar; ---> bar is null
```

Please can you advice what is the right way to inject this value for my test cases?
Java v17, Springboot v3, Junit v5, system-stubs v2.1.3, MacOS M1

**Comment by ashleyfrieze** [comment]
@vvijayalakshmi21 - I'm assuming this is a Spring test and that the above code is your Spring production code.

Please show me the test fixture and how you're trying to set the environment variable using system stubs.

**Comment by ashleyfrieze** [comment]
@vvijayalakshmi21 - I'll close this in a couple of days if I haven't heard from you. There's an example Spring test here - https://github.com/webcompere/system-stubs/blob/main/system-stubs-jupiter/src/test/java/uk/org/webcompere/systemstubs/jupiter/examples/SpringAppWithDynamicPropertiesTest.java

**Comment by vvijayalakshmi21** [comment]
Apologies for the delay in response. 
Let me go through the example.
