### ISSUE TITLE
Java 22 upgrade needed for bytebuddy

### ISSUE THREAD

**Issue by prasaanth-hbo** [webcompere/system-stubs#87]
java.lang.NoClassDefFoundError: Could not initialize class uk.org.webcompere.systemstubs.environment.EnvironmentVariableMocker
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Cannot set up environment mocking: Java 22 (66) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property. [in thread "main"]

We get this from the maven surefire plugin when we try to run tests.

Any workaround for this?

**Comment by ashleyfrieze** [comment]
@prasaanth-hbo - as a first guess, I'd say that we need to version bump ByteBuddy to a more recent one. If you want to submit a PR, please do so. I'll look into it later when I have time. Let me know if you're going to submit a PR.

**Comment by prasaanth-hbo** [comment]
Here is a PR for the version bump. Bumping to 1.15.0 (latest is at 1.15.1) though 1.14.16 has the Java compatibility changes.  

https://github.com/webcompere/system-stubs/pull/88/files

**Comment by ashleyfrieze** [comment]
Release scheduled - will be in maven central in a few hours.

**Comment by ashleyfrieze** [comment]
@prasaanth-hbo https://repo1.maven.org/maven2/uk/org/webcompere/system-stubs-core/2.1.7/
