### ISSUE TITLE
What is the current status of `1.x`?

### ISSUE THREAD

**Issue by yeikel** [webcompere/system-stubs#92]
Hi team, 

What is the current status of the `1.x` version? Could you please clarify if it reached end of life?  

From what I understand, the dev team of this project is small and as stated before, I am very appreciative of the `1.2.1` release to support me with https://github.com/webcompere/system-stubs/issues/84

Namely changes like https://github.com/webcompere/system-stubs/releases/tag/system-stubs-parent-2.1.7 are interesting to us who are still stuck with 1.x for the foreseeable future. Upgrading is difficult and will still take us some time

**Comment by ashleyfrieze** [comment]
@yeikel the reality is that the `1.x` branch is a long-term branch, but it takes effort to release and maintain. I think you're the only user who needs that branch. What specifically is the problem you're facing. Bytebuddy shouldn't be part of the 1.x world.

I'm happy for you to raise issues about specific problems you're facing, and I'll try to accept relevant PRs too.
